var mbtiQuestions = {
  short: [
    { id: 1, text: "在聚会中，你通常：", dimension: "EI", optionA: "与许多人交谈，包括陌生人", optionB: "只与少数几个认识的人交谈" },
    { id: 2, text: "你更倾向于：", dimension: "SN", optionA: "关注现实和具体的事实", optionB: "关注可能性和未来的发展" },
    { id: 3, text: "做决定时，你更重视：", dimension: "TF", optionA: "逻辑和客观分析", optionB: "个人价值观和他人感受" },
    { id: 4, text: "你更喜欢的生活方式是：", dimension: "JP", optionA: "有计划、有组织", optionB: "灵活、随性" },
    { id: 5, text: "你觉得被什么所激励：", dimension: "EI", optionA: "社交活动和与人互动", optionB: "独处和安静的环境" },
    { id: 6, text: "你更关注：", dimension: "SN", optionA: "眼前的具体细节", optionB: "整体的模式和含义" },
    { id: 7, text: "你认为更重要的是：", dimension: "TF", optionA: "公正和一致性", optionB: "同情和理解" },
    { id: 8, text: "你做事的方式是：", dimension: "JP", optionA: "提前安排好一切", optionB: "随机应变" },
    { id: 9, text: "在工作中，你更喜欢：", dimension: "EI", optionA: "团队合作", optionB: "独立工作" },
    { id: 10, text: "你更信任：", dimension: "SN", optionA: "亲身经历和实际经验", optionB: "直觉和第六感" },
    { id: 11, text: "别人认为你是：", dimension: "TF", optionA: "理性、客观的人", optionB: "感性、有同情心的人" },
    { id: 12, text: "你对待截止日期的态度是：", dimension: "JP", optionA: "提前完成", optionB: "最后一刻才完成" },
    { id: 13, text: "你更享受：", dimension: "EI", optionA: "大型聚会和活动", optionB: "小型聚会或一对一交流" },
    { id: 14, text: "你更擅长：", dimension: "SN", optionA: "处理具体的、实际的问题", optionB: "构想新的概念和想法" },
    { id: 15, text: "你更看重：", dimension: "TF", optionA: "效率和成果", optionB: "和谐与人际关系" },
    { id: 16, text: "你的工作空间通常是：", dimension: "JP", optionA: "整洁有序", optionB: "有创意的混乱" },
    { id: 17, text: "你认识新朋友的方式是：", dimension: "EI", optionA: "主动介绍自己", optionB: "等别人来认识你" },
    { id: 18, text: "你更喜欢的老师是：", dimension: "SN", optionA: "讲解清晰、注重实际应用", optionB: "启发思考、鼓励创新" },
    { id: 19, text: "在冲突中，你倾向于：", dimension: "TF", optionA: "坚持原则和事实", optionB: "寻求妥协和共识" },
    { id: 20, text: "你旅行时更喜欢：", dimension: "JP", optionA: "提前规划好行程", optionB: "到了再决定做什么" },
    { id: 21, text: "你更喜欢的休闲方式是：", dimension: "EI", optionA: "参加社交活动", optionB: "在家看书或看电影" },
    { id: 22, text: "你更关注：", dimension: "SN", optionA: "当下正在发生的事", optionB: "未来的可能性" },
    { id: 23, text: "你做选择时更依赖：", dimension: "TF", optionA: "逻辑分析", optionB: "内心感受" },
    { id: 24, text: "你的日常安排是：", dimension: "JP", optionA: "固定的、可预测的", optionB: "多变的、灵活的" },
    { id: 25, text: "在社交场合，你：", dimension: "EI", optionA: "容易感到精力充沛", optionB: "容易感到疲惫" },
    { id: 26, text: "你更喜欢讨论：", dimension: "SN", optionA: "具体的事实和数据", optionB: "理论和概念" },
    { id: 27, text: "你更难接受的是：", dimension: "TF", optionA: "不合逻辑的决定", optionB: "伤害他人感情" },
    { id: 28, text: "你更喜欢的工作环境是：", dimension: "JP", optionA: "结构清晰、目标明确", optionB: "灵活自由、有创意空间" },
    { id: 29, text: "你更倾向于：", dimension: "EI", optionA: "先行动后思考", optionB: "先思考后行动" },
    { id: 30, text: "你更喜欢阅读：", dimension: "SN", optionA: "非虚构类、实用性的书籍", optionB: "小说、科幻或哲学类书籍" },
    { id: 31, text: "你更欣赏的品质是：", dimension: "TF", optionA: "坚定和果断", optionB: "善良和体贴" },
    { id: 32, text: "你对待规则的态度是：", dimension: "JP", optionA: "遵守规则很重要", optionB: "规则可以灵活处理" },
    { id: 33, text: "你在电话中：", dimension: "EI", optionA: "喜欢长时间聊天", optionB: "倾向于简短通话" },
    { id: 34, text: "你更相信：", dimension: "SN", optionA: "眼见为实", optionB: "预感和直觉" },
    { id: 35, text: "你更愿意被称为：", dimension: "TF", optionA: "有逻辑的人", optionB: "有同情心的人" },
    { id: 36, text: "你更喜欢的假期是：", dimension: "JP", optionA: "提前规划好一切", optionB: "到了目的地再决定" }
  ],
  long: [
    { id: 1, text: "在聚会中，你通常：", dimension: "EI", optionA: "与许多人交谈，包括陌生人", optionB: "只与少数几个认识的人交谈" },
    { id: 2, text: "你更倾向于：", dimension: "SN", optionA: "关注现实和具体的事实", optionB: "关注可能性和未来的发展" },
    { id: 3, text: "做决定时，你更重视：", dimension: "TF", optionA: "逻辑和客观分析", optionB: "个人价值观和他人感受" },
    { id: 4, text: "你更喜欢的生活方式是：", dimension: "JP", optionA: "有计划、有组织", optionB: "灵活、随性" },
    { id: 5, text: "你觉得被什么所激励：", dimension: "EI", optionA: "社交活动和与人互动", optionB: "独处和安静的环境" },
    { id: 6, text: "你更关注：", dimension: "SN", optionA: "眼前的具体细节", optionB: "整体的模式和含义" },
    { id: 7, text: "你认为更重要的是：", dimension: "TF", optionA: "公正和一致性", optionB: "同情和理解" },
    { id: 8, text: "你做事的方式是：", dimension: "JP", optionA: "提前安排好一切", optionB: "随机应变" },
    { id: 9, text: "在工作中，你更喜欢：", dimension: "EI", optionA: "团队合作", optionB: "独立工作" },
    { id: 10, text: "你更信任：", dimension: "SN", optionA: "亲身经历和实际经验", optionB: "直觉和第六感" },
    { id: 11, text: "别人认为你是：", dimension: "TF", optionA: "理性、客观的人", optionB: "感性、有同情心的人" },
    { id: 12, text: "你对待截止日期的态度是：", dimension: "JP", optionA: "提前完成", optionB: "最后一刻才完成" },
    { id: 13, text: "你更享受：", dimension: "EI", optionA: "大型聚会和活动", optionB: "小型聚会或一对一交流" },
    { id: 14, text: "你更擅长：", dimension: "SN", optionA: "处理具体的、实际的问题", optionB: "构想新的概念和想法" },
    { id: 15, text: "你更看重：", dimension: "TF", optionA: "效率和成果", optionB: "和谐与人际关系" },
    { id: 16, text: "你的工作空间通常是：", dimension: "JP", optionA: "整洁有序", optionB: "有创意的混乱" },
    { id: 17, text: "你认识新朋友的方式是：", dimension: "EI", optionA: "主动介绍自己", optionB: "等别人来认识你" },
    { id: 18, text: "你更喜欢的老师是：", dimension: "SN", optionA: "讲解清晰、注重实际应用", optionB: "启发思考、鼓励创新" },
    { id: 19, text: "在冲突中，你倾向于：", dimension: "TF", optionA: "坚持原则和事实", optionB: "寻求妥协和共识" },
    { id: 20, text: "你旅行时更喜欢：", dimension: "JP", optionA: "提前规划好行程", optionB: "到了再决定做什么" },
    { id: 21, text: "你更喜欢的休闲方式是：", dimension: "EI", optionA: "参加社交活动", optionB: "在家看书或看电影" },
    { id: 22, text: "你更关注：", dimension: "SN", optionA: "当下正在发生的事", optionB: "未来的可能性" },
    { id: 23, text: "你做选择时更依赖：", dimension: "TF", optionA: "逻辑分析", optionB: "内心感受" },
    { id: 24, text: "你的日常安排是：", dimension: "JP", optionA: "固定的、可预测的", optionB: "多变的、灵活的" },
    { id: 25, text: "在社交场合，你：", dimension: "EI", optionA: "容易感到精力充沛", optionB: "容易感到疲惫" },
    { id: 26, text: "你更喜欢讨论：", dimension: "SN", optionA: "具体的事实和数据", optionB: "理论和概念" },
    { id: 27, text: "你更难接受的是：", dimension: "TF", optionA: "不合逻辑的决定", optionB: "伤害他人感情" },
    { id: 28, text: "你更喜欢的工作环境是：", dimension: "JP", optionA: "结构清晰、目标明确", optionB: "灵活自由、有创意空间" },
    { id: 29, text: "你更倾向于：", dimension: "EI", optionA: "先行动后思考", optionB: "先思考后行动" },
    { id: 30, text: "你更喜欢阅读：", dimension: "SN", optionA: "非虚构类、实用性的书籍", optionB: "小说、科幻或哲学类书籍" },
    { id: 31, text: "你更欣赏的品质是：", dimension: "TF", optionA: "坚定和果断", optionB: "善良和体贴" },
    { id: 32, text: "你对待规则的态度是：", dimension: "JP", optionA: "遵守规则很重要", optionB: "规则可以灵活处理" },
    { id: 33, text: "你在电话中：", dimension: "EI", optionA: "喜欢长时间聊天", optionB: "倾向于简短通话" },
    { id: 34, text: "你更相信：", dimension: "SN", optionA: "眼见为实", optionB: "预感和直觉" },
    { id: 35, text: "你更愿意被称为：", dimension: "TF", optionA: "有逻辑的人", optionB: "有同情心的人" },
    { id: 36, text: "你更喜欢的假期是：", dimension: "JP", optionA: "提前规划好一切", optionB: "到了目的地再决定" },
    { id: 37, text: "你在派对上：", dimension: "EI", optionA: "喜欢认识新朋友", optionB: "喜欢和老朋友在一起" },
    { id: 38, text: "你更喜欢的电影类型是：", dimension: "SN", optionA: "基于真实事件的电影", optionB: "科幻或奇幻电影" },
    { id: 39, text: "你更看重的是：", dimension: "TF", optionA: "真理和正义", optionB: "慈悲和宽恕" },
    { id: 40, text: "你更喜欢的购物方式是：", dimension: "JP", optionA: "列好清单，按计划购买", optionB: "随意逛，看到喜欢的就买" },
    { id: 41, text: "你在空闲时间更喜欢：", dimension: "EI", optionA: "外出活动", optionB: "待在家里" },
    { id: 42, text: "你更喜欢的课程是：", dimension: "SN", optionA: "有明确答案的课程", optionB: "鼓励独立思考的课程" },
    { id: 43, text: "你更倾向于：", dimension: "TF", optionA: "用逻辑说服别人", optionB: "用情感打动别人" },
    { id: 44, text: "你更喜欢的领导风格是：", dimension: "JP", optionA: "明确的指令和期望", optionB: "灵活的指导和自由" },
    { id: 45, text: "你更喜欢：", dimension: "EI", optionA: "热闹的环境", optionB: "安静的环境" },
    { id: 46, text: "你更感兴趣的是：", dimension: "SN", optionA: "已经发生的事", optionB: "可能发生的事" },
    { id: 47, text: "你更难忍受的是：", dimension: "TF", optionA: "不公正", optionB: "不友善" },
    { id: 48, text: "你更喜欢的项目管理方式是：", dimension: "JP", optionA: "制定详细的计划", optionB: "边做边调整" },
    { id: 49, text: "你在社交中：", dimension: "EI", optionA: "主动发起对话", optionB: "等待别人来找你" },
    { id: 50, text: "你更喜欢的解决问题方式是：", dimension: "SN", optionA: "按部就班地分析", optionB: "跳跃性地思考" },
    { id: 51, text: "你更看重的是：", dimension: "TF", optionA: "能力和成就", optionB: "人际关系和和谐" },
    { id: 52, text: "你更喜欢的生活节奏是：", dimension: "JP", optionA: "稳定、可预测", optionB: "多变、刺激" },
    { id: 53, text: "你更喜欢的交流方式是：", dimension: "EI", optionA: "面对面交谈", optionB: "文字交流" },
    { id: 54, text: "你更喜欢的学习方式是：", dimension: "SN", optionA: "实践操作", optionB: "理论学习" },
    { id: 55, text: "你更倾向于：", dimension: "TF", optionA: "客观地评价事物", optionB: "主观地感受事物" },
    { id: 56, text: "你更喜欢的日程安排是：", dimension: "JP", optionA: "提前安排好", optionB: "随性而为" },
    { id: 57, text: "你更喜欢的工作方式是：", dimension: "EI", optionA: "与同事讨论", optionB: "独自思考" },
    { id: 58, text: "你更关注的是：", dimension: "SN", optionA: "具体的事实", optionB: "抽象的概念" },
    { id: 59, text: "你更看重的决策依据是：", dimension: "TF", optionA: "数据和证据", optionB: "价值观和信念" },
    { id: 60, text: "你更喜欢的结束方式是：", dimension: "JP", optionA: "有明确的结论", optionB: "保持开放的可能性" },
    { id: 61, text: "你在团队中更喜欢：", dimension: "EI", optionA: "担任领导角色", optionB: "担任支持角色" },
    { id: 62, text: "你更喜欢的写作方式是：", dimension: "SN", optionA: "写实、具体的描述", optionB: "富有想象力的表达" },
    { id: 63, text: "你更难做到的是：", dimension: "TF", optionA: "忽视逻辑做出情感化决定", optionB: "忽视情感做出纯理性决定" },
    { id: 64, text: "你更喜欢的周末是：", dimension: "JP", optionA: "提前安排好活动", optionB: "临时决定做什么" },
    { id: 65, text: "你在新环境中：", dimension: "EI", optionA: "很快就能适应", optionB: "需要时间来适应" },
    { id: 66, text: "你更喜欢的故事类型是：", dimension: "SN", optionA: "贴近生活的故事", optionB: "充满奇幻元素的故事" },
    { id: 67, text: "你更倾向于认为：", dimension: "TF", optionA: "公平比同情更重要", optionB: "同情比公平更重要" },
    { id: 68, text: "你更喜欢的约会方式是：", dimension: "JP", optionA: "提前计划好一切", optionB: "随性而为" },
    { id: 69, text: "你在人群中：", dimension: "EI", optionA: "很容易被注意到", optionB: "不太引人注目" },
    { id: 70, text: "你更喜欢的哲学观点是：", dimension: "SN", optionA: "实践出真知", optionB: "思考出真知" },
    { id: 71, text: "你更欣赏的领导品质是：", dimension: "TF", optionA: "果断和效率", optionB: "关怀和理解" },
    { id: 72, text: "你更喜欢的生活状态是：", dimension: "JP", optionA: "井井有条", optionB: "自由自在" },
    { id: 73, text: "你在社交网络上：", dimension: "EI", optionA: "经常发布动态", optionB: "很少发布动态" },
    { id: 74, text: "你更喜欢的音乐类型是：", dimension: "SN", optionA: "歌词有意义的音乐", optionB: "旋律优美的音乐" },
    { id: 75, text: "你更难接受的批评是：", dimension: "TF", optionA: "说你不讲道理", optionB: "说你不够关心人" },
    { id: 76, text: "你更喜欢的工作时间是：", dimension: "JP", optionA: "固定的上下班时间", optionB: "灵活的工作时间" },
    { id: 77, text: "你在朋友聚会中：", dimension: "EI", optionA: "是活跃气氛的人", optionB: "是安静倾听的人" },
    { id: 78, text: "你更喜欢的艺术形式是：", dimension: "SN", optionA: "写实主义", optionB: "抽象主义" },
    { id: 79, text: "你更倾向于：", dimension: "TF", optionA: "就事论事", optionB: "考虑人的因素" },
    { id: 80, text: "你更喜欢的整理方式是：", dimension: "JP", optionA: "分类整理，物归原位", optionB: "随手放，需要时再找" },
    { id: 81, text: "你在旅行中：", dimension: "EI", optionA: "喜欢结伴同行", optionB: "喜欢独自旅行" },
    { id: 82, text: "你更喜欢的运动是：", dimension: "SN", optionA: "有明确规则的运动", optionB: "自由发挥的运动" },
    { id: 83, text: "你更看重员工的：", dimension: "TF", optionA: "工作能力", optionB: "工作态度" },
    { id: 84, text: "你更喜欢的婚礼是：", dimension: "JP", optionA: "精心策划的", optionB: "简单随意的" },
    { id: 85, text: "你在演讲时：", dimension: "EI", optionA: "感到兴奋和自信", optionB: "感到紧张和不安" },
    { id: 86, text: "你更喜欢的纪录片类型是：", dimension: "SN", optionA: "科学和历史类", optionB: "哲学和心理类" },
    { id: 87, text: "你更倾向于：", dimension: "TF", optionA: "做出艰难但正确的决定", optionB: "做出让大家都开心的决定" },
    { id: 88, text: "你更喜欢的派对是：", dimension: "JP", optionA: "有组织的活动", optionB: "自由交流的" },
    { id: 89, text: "你在工作中更喜欢：", dimension: "EI", optionA: "开放式的办公环境", optionB: "独立的办公空间" },
    { id: 90, text: "你更喜欢的书是：", dimension: "SN", optionA: "实用指南类", optionB: "思想启发类" },
    { id: 91, text: "你更难做到的是：", dimension: "TF", optionA: "对事不对人", optionB: "不考虑后果地帮助他人" },
    { id: 92, text: "你更喜欢的交通方式是：", dimension: "JP", optionA: "提前规划好路线", optionB: "随遇而安" },
    { id: 93, text: "你在社交媒体上：", dimension: "EI", optionA: "有很多好友", optionB: "只有少量好友" },
    { id: 94, text: "你更喜欢的天气是：", dimension: "SN", optionA: "阳光明媚", optionB: "阴雨绵绵" },
    { id: 95, text: "你更倾向于：", dimension: "TF", optionA: "保持客观中立", optionB: "表达个人情感" },
    { id: 96, text: "你更喜欢的节日庆祝方式是：", dimension: "JP", optionA: "按照传统来", optionB: "创造新的方式" },
    { id: 97, text: "你在课堂上：", dimension: "EI", optionA: "积极发言", optionB: "安静听讲" },
    { id: 98, text: "你更喜欢的餐厅是：", dimension: "SN", optionA: "菜品稳定的", optionB: "经常创新的" },
    { id: 99, text: "你更看重朋友的：", dimension: "TF", optionA: "诚实和直率", optionB: "体贴和关心" },
    { id: 100, text: "你更喜欢的购物体验是：", dimension: "JP", optionA: "有明确目标", optionB: "随意浏览" },
    { id: 101, text: "你在陌生城市：", dimension: "EI", optionA: "喜欢问路和交流", optionB: "喜欢自己探索" },
    { id: 102, text: "你更喜欢的科学是：", dimension: "SN", optionA: "实验科学", optionB: "理论科学" },
    { id: 103, text: "你更倾向于：", dimension: "TF", optionA: "用数据说话", optionB: "用感受说话" },
    { id: 104, text: "你更喜欢的宠物是：", dimension: "JP", optionA: "有规律作息的", optionB: "活泼好动的" },
    { id: 105, text: "你在会议上：", dimension: "EI", optionA: "主动发言", optionB: "等被点名" },
    { id: 106, text: "你更喜欢的电影结局是：", dimension: "SN", optionA: "明确的结局", optionB: "开放式的结局" },
    { id: 107, text: "你更难做到的是：", dimension: "TF", optionA: "撒善意的谎言", optionB: "说出残酷的真相" },
    { id: 108, text: "你更喜欢的存钱方式是：", dimension: "JP", optionA: "定期存款", optionB: "随时存取" },
    { id: 109, text: "你在派对结束后：", dimension: "EI", optionA: "感到精力充沛", optionB: "感到筋疲力尽" },
    { id: 110, text: "你更喜欢的数学是：", dimension: "SN", optionA: "应用数学", optionB: "纯数学" },
    { id: 111, text: "你更倾向于：", dimension: "TF", optionA: "追求效率", optionB: "追求和谐" },
    { id: 112, text: "你更喜欢的退休生活是：", dimension: "JP", optionA: "有计划的", optionB: "自由的" },
    { id: 113, text: "你在新公司：", dimension: "EI", optionA: "很快和同事打成一片", optionB: "需要较长时间融入" },
    { id: 114, text: "你更喜欢的建筑风格是：", dimension: "SN", optionA: "实用主义", optionB: "艺术创新" },
    { id: 115, text: "你更看重：", dimension: "TF", optionA: "真理", optionB: "善良" },
    { id: 116, text: "你更喜欢的日历是：", dimension: "JP", optionA: "纸质日历", optionB: "电子日历" },
    { id: 117, text: "你在团队项目中：", dimension: "EI", optionA: "喜欢讨论和协作", optionB: "喜欢分工独立完成" },
    { id: 118, text: "你更喜欢的旅游方式是：", dimension: "SN", optionA: "跟团游", optionB: "自由行" },
    { id: 119, text: "你更倾向于：", dimension: "TF", optionA: "批评指正", optionB: "鼓励支持" },
    { id: 120, text: "你更喜欢的人生是：", dimension: "JP", optionA: "按计划进行", optionB: "充满惊喜" }
  ]
};

var mbtiTypes = {
  "INTJ": {
    name: "建筑师",
    nickname: "INTJ - 建筑师",
    category: "analyst",
    description: "INTJ是富有想象力和战略性的思想家，一切皆在计划之中。他们是独立、有远见的人，善于将复杂的想法转化为可执行的计划。INTJ追求知识和能力，不断寻求改进和优化系统。",
    traits: ["独立思考者", "战略性强", "追求效率", "高标准", "有远见"],
    strengths: ["战略规划能力强", "独立自主", "意志坚定", "富有创造力", "善于分析"],
    weaknesses: ["可能过于理性", "对他人情感不够敏感", "完美主义", "可能显得傲慢"],
    careers: ["科学家", "系统架构师", "投资分析师", "战略顾问", "软件工程师"]
  },
  "INTP": {
    name: "逻辑学家",
    nickname: "INTP - 逻辑学家",
    category: "analyst",
    description: "INTP是具有创造力的发明家，对知识有着永不满足的渴望。他们是理论性的思想家，喜欢探索抽象的概念和复杂的理论。INTP重视逻辑和理性，追求理解事物的本质。",
    traits: ["逻辑性强", "理论思考", "创新", "独立", "好奇"],
    strengths: ["分析能力强", "客观公正", "创新思维", "善于解决复杂问题", "学习能力强"],
    weaknesses: ["可能过于理论化", "社交能力较弱", "拖延症", "对细节不够关注"],
    careers: ["数学家", "程序员", "物理学家", "哲学家", "研究科学家"]
  },
  "ENTJ": {
    name: "指挥官",
    nickname: "ENTJ - 指挥官",
    category: "analyst",
    description: "ENTJ是大胆、富有想象力和意志力的领导者，总能找到或创造解决方法。他们是天生的领导者，善于组织和推动团队实现目标。ENTJ追求效率和成果，具有强烈的目标导向。",
    traits: ["领导力强", "果断", "有远见", "高效", "自信"],
    strengths: ["领导能力出色", "战略思维", "决策果断", "高效执行", "激励他人"],
    weaknesses: ["可能过于强势", "缺乏耐心", "对情感不够敏感", "工作狂"],
    careers: ["CEO", "律师", "管理顾问", "企业家", "政治家"]
  },
  "ENTP": {
    name: "辩论家",
    nickname: "ENTP - 辩论家",
    category: "analyst",
    description: "ENTP是聪明好奇的思想家，不会放过任何智力挑战。他们是创新者和问题解决者，喜欢探索新的可能性。ENTP善于辩论，享受思想的碰撞。",
    traits: ["聪明", "好奇", "善于辩论", "创新", "灵活"],
    strengths: ["思维敏捷", "创新能力强", "适应力强", "善于激励他人", "多才多艺"],
    weaknesses: ["可能过于好辩", "注意力分散", "拖延症", "对细节不够关注"],
    careers: ["律师", "企业家", "创意总监", "记者", "工程师"]
  },
  "INFJ": {
    name: "提倡者",
    nickname: "INFJ - 提倡者",
    category: "diplomat",
    description: "INFJ是安静而神秘的理想主义者，同时鼓舞人心且不知疲倦。他们是理想主义者，致力于帮助他人和改善世界。INFJ具有深刻的洞察力和强烈的同理心。",
    traits: ["有远见", "有同理心", "理想主义", "有条理", "有决心"],
    strengths: ["洞察力强", "有同理心", "有远见", "坚定", "善于激励他人"],
    weaknesses: ["完美主义", "对批评敏感", "可能过于理想化", "容易疲惫"],
    careers: ["心理咨询师", "作家", "社会工作者", "教师", "人力资源"]
  },
  "INFP": {
    name: "调停者",
    nickname: "INFP - 调停者",
    category: "diplomat",
    description: "INFP是诗意、善良的利他主义者，总是热情地为正当理由提供帮助。他们是理想主义者，重视个人价值观和内在和谐。INFP富有创造力和想象力。",
    traits: ["理想主义", "有创造力", "有同理心", "忠诚", "适应力强"],
    strengths: ["富有创造力", "有同理心", "开放包容", "忠诚", "善于理解他人"],
    weaknesses: ["可能过于理想化", "逃避现实", "情绪化", "自我批评"],
    careers: ["作家", "艺术家", "心理咨询师", "社会工作者", "音乐家"]
  },
  "ENFJ": {
    name: "主人公",
    nickname: "ENFJ - 主人公",
    category: "diplomat",
    description: "ENFJ是富有魅力和鼓舞人心的领导者，能够迷住其听众。他们是天生的领导者，善于激励和引导他人。ENFJ重视人际关系，致力于帮助他人成长。",
    traits: ["有魅力", "有同理心", "有组织能力", "可靠", "利他主义"],
    strengths: ["领导力强", "有同理心", "善于激励他人", "组织能力强", "可靠"],
    weaknesses: ["可能过于理想化", "自我牺牲", "对批评敏感", "可能过于控制"],
    careers: ["教师", "销售经理", "政治家", "培训师", "公关专家"]
  },
  "ENFP": {
    name: "竞选者",
    nickname: "ENFP - 竞选者",
    category: "diplomat",
    description: "ENFP是热情、有创造力和社交能力的自由精神，总能找到微笑的理由。他们是充满活力的人，喜欢探索新的可能性。ENFP富有创造力和感染力。",
    traits: ["热情", "有创造力", "社交能力强", "好奇", "有活力"],
    strengths: ["热情洋溢", "有创造力", "善于社交", "适应力强", "善于激励他人"],
    weaknesses: ["注意力分散", "过于理想化", "情绪化", "可能不够专注"],
    careers: ["记者", "演员", "创意总监", "心理咨询师", "企业家"]
  },
  "ISTJ": {
    name: "物流师",
    nickname: "ISTJ - 物流师",
    category: "sentinel",
    description: "ISTJ是实际且注重事实的个人，其可靠性不容怀疑。他们是负责任、有条理的人，重视传统和秩序。ISTJ善于执行计划，注重细节。",
    traits: ["可靠", "有条理", "实际", "负责", "传统"],
    strengths: ["可靠负责", "有条理", "注重细节", "意志坚定", "诚实"],
    weaknesses: ["可能过于刻板", "对新事物不够开放", "过于严肃", "可能忽视他人感受"],
    careers: ["会计师", "审计员", "项目经理", "军事人员", "公务员"]
  },
  "ISFJ": {
    name: "守卫者",
    nickname: "ISFJ - 守卫者",
    category: "sentinel",
    description: "ISFJ是温暖而专注的保护者，时刻准备着保护所爱的人。他们是可靠、有责任心的人，重视和谐与稳定。ISFJ善于照顾他人，注重细节。",
    traits: ["温暖", "有责任心", "可靠", "注重细节", "忠诚"],
    strengths: ["有责任心", "可靠", "有同理心", "注重细节", "忠诚"],
    weaknesses: ["可能过于自我牺牲", "对变化不够适应", "可能过于传统", "难以拒绝他人"],
    careers: ["护士", "教师", "行政助理", "社会工作者", "图书管理员"]
  },
  "ESTJ": {
    name: "总经理",
    nickname: "ESTJ - 总经理",
    category: "sentinel",
    description: "ESTJ是出色的管理者，在管理事物或人的方面无与伦比。他们是实际、有条理的领导者，重视秩序和效率。ESTJ善于组织和执行。",
    traits: ["实际", "有条理", "可靠", "果断", "传统"],
    strengths: ["组织能力强", "可靠负责", "果断", "注重效率", "诚实"],
    weaknesses: ["可能过于刻板", "对情感不够敏感", "可能过于控制", "对新事物不够开放"],
    careers: ["经理", "军官", "法官", "学校校长", "银行家"]
  },
  "ESFJ": {
    name: "执政官",
    nickname: "ESFJ - 执政官",
    category: "sentinel",
    description: "ESFJ是非常关心他人的人，社交能力极强，受欢迎且热衷于帮助别人。他们是温暖、有责任心的人，重视和谐与合作。ESFJ善于照顾他人。",
    traits: ["温暖", "有责任心", "社交能力强", "合作", "忠诚"],
    strengths: ["有同理心", "可靠负责", "善于社交", "组织能力强", "忠诚"],
    weaknesses: ["可能过于自我牺牲", "对批评敏感", "可能过于传统", "需要他人认可"],
    careers: ["护士", "教师", "销售代表", "人力资源", "社工"]
  },
  "ISTP": {
    name: "鉴赏家",
    nickname: "ISTP - 鉴赏家",
    category: "explorer",
    description: "ISTP是大胆而实际的实验家，擅长使用各种形式的工具。他们是灵活、实际的问题解决者，喜欢探索事物如何运作。ISTP重视自由和效率。",
    traits: ["实际", "灵活", "独立", "观察力强", "冷静"],
    strengths: ["问题解决能力强", "实际", "灵活", "独立", "冷静"],
    weaknesses: ["可能过于冷漠", "冒险", "对承诺不够坚定", "可能忽视他人感受"],
    careers: ["工程师", "飞行员", "消防员", "法医", "技工"]
  },
  "ISFP": {
    name: "探险家",
    nickname: "ISFP - 探险家",
    category: "explorer",
    description: "ISFP是灵活有魅力的艺术家，时刻准备着探索和体验新事物。他们是温和、敏感的人，重视个人价值观和美学。ISFP富有创造力和同理心。",
    traits: ["温和", "敏感", "有创造力", "灵活", "有同理心"],
    strengths: ["有创造力", "有同理心", "灵活", "善于观察", "忠诚"],
    weaknesses: ["可能过于敏感", "逃避冲突", "可能缺乏长期规划", "自我批评"],
    careers: ["艺术家", "设计师", "音乐家", "摄影师", "兽医"]
  },
  "ESTP": {
    name: "企业家",
    nickname: "ESTP - 企业家",
    category: "explorer",
    description: "ESTP是聪明、精力充沛和非常善于感知的人，真正享受活在边缘。他们是实际、灵活的人，喜欢行动和冒险。ESTP善于解决问题和抓住机会。",
    traits: ["精力充沛", "实际", "灵活", "善于社交", "大胆"],
    strengths: ["精力充沛", "实际", "灵活", "善于解决问题", "适应力强"],
    weaknesses: ["可能冲动", "对长期规划不够重视", "可能忽视他人感受", "容易感到无聊"],
    careers: ["企业家", "销售", "运动员", "警察", "消防员"]
  },
  "ESFP": {
    name: "表演者",
    nickname: "ESFP - 表演者",
    category: "explorer",
    description: "ESFP是自发的、精力充沛和热情的娱乐者——生活永远不会和他们在一起时无聊。他们是热情、有趣的人，喜欢成为关注的焦点。ESFP善于社交和娱乐他人。",
    traits: ["热情", "有活力", "善于社交", "有趣", "灵活"],
    strengths: ["热情洋溢", "善于社交", "有活力", "乐观", "善于激励他人"],
    weaknesses: ["可能冲动", "注意力分散", "可能逃避问题", "对长期规划不够重视"],
    careers: ["演员", "歌手", "销售", "公关", "旅游顾问"]
  }
};