var bsriItems = [
  { id: 1, text: "自立的", type: "masculine" },
  { id: 2, text: "顺从的", type: "feminine" },
  { id: 3, text: "乐于助人的", type: "feminine" },
  { id: 4, text: "维护自己信念的", type: "masculine" },
  { id: 5, text: "欢快的", type: "feminine" },
  { id: 6, text: "心情易变的", type: "feminine" },
  { id: 7, text: "独立的", type: "masculine" },
  { id: 8, text: "害羞的", type: "feminine" },
  { id: 9, text: "有同情心的", type: "feminine" },
  { id: 10, text: "坚定的", type: "masculine" },
  { id: 11, text: "有忠诚度的", type: "feminine" },
  { id: 12, text: "有竞争心的", type: "masculine" },
  { id: 13, text: "有孩子气的", type: "neutral" },
  { id: 14, text: "有立场的", type: "masculine" },
  { id: 15, text: "爱奉承的", type: "feminine" },
  { id: 16, text: "可靠的", type: "neutral" },
  { id: 17, text: "有男子气概的", type: "masculine" },
  { id: 18, text: "有冒险精神的", type: "masculine" },
  { id: 19, text: "理解他人的", type: "feminine" },
  { id: 20, text: "有秘密的", type: "neutral" },
  { id: 21, text: "果断的", type: "masculine" },
  { id: 22, text: "有同情心的", type: "feminine" },
  { id: 23, text: "真诚的", type: "neutral" },
  { id: 24, text: "有个性的", type: "neutral" },
  { id: 25, text: "有力量的", type: "masculine" },
  { id: 26, text: "有女性气质的", type: "feminine" },
  { id: 27, text: "值得信赖的", type: "neutral" },
  { id: 28, text: "有分析力的", type: "masculine" },
  { id: 29, text: "有感情的", type: "feminine" },
  { id: 30, text: "精明的", type: "masculine" },
  { id: 31, text: "有尊严的", type: "neutral" },
  { id: 32, text: "有爱心的", type: "feminine" },
  { id: 33, text: "爱冒风险的", type: "masculine" },
  { id: 34, text: "冷淡的", type: "neutral" },
  { id: 35, text: "有适应力的", type: "neutral" },
  { id: 36, text: "有领导力的", type: "masculine" },
  { id: 37, text: "敏感的", type: "feminine" },
  { id: 38, text: "诚实的", type: "neutral" },
  { id: 39, text: "有主见的", type: "masculine" },
  { id: 40, text: "温柔的", type: "feminine" },
  { id: 41, text: "有个性的", type: "neutral" },
  { id: 42, text: "有攻击性的", type: "masculine" },
  { id: 43, text: "可爱的", type: "feminine" },
  { id: 44, text: "有野心的", type: "masculine" },
  { id: 45, text: "有教养的", type: "neutral" },
  { id: 46, text: "忠诚的", type: "feminine" },
  { id: 47, text: "有能力的", type: "neutral" },
  { id: 48, text: "有考虑的", type: "feminine" },
  { id: 49, text: "有竞争力的", type: "masculine" },
  { id: 50, text: "有爱心的", type: "feminine" },
  { id: 51, text: "有志气的", type: "masculine" },
  { id: 52, text: "有温和的", type: "feminine" },
  { id: 53, text: "有传统观念的", type: "neutral" },
  { id: 54, text: "有主动性的", type: "masculine" },
  { id: 55, text: "有柔顺的", type: "feminine" },
  { id: 56, text: "有友善的", type: "neutral" },
  { id: 57, text: "有个性的", type: "neutral" },
  { id: 58, text: "有强势的", type: "masculine" },
  { id: 59, text: "有顺从的", type: "feminine" },
  { id: 60, text: "有快乐的", type: "neutral" }
];

var genderTypes = {
  masculine: {
    name: "男性化",
    icon: "♂️",
    color: "#3b82f6",
    description: "你的心理性别角色偏向男性化。你具有较强的独立性、决断力和竞争意识，善于领导和承担责任。你在面对挑战时表现出坚定和自信。",
    traits: ["独立自主", "果断坚定", "有领导力", "有竞争意识", "善于承担责任"],
    strengths: ["决策能力强", "执行力强", "抗压能力强", "目标导向", "善于解决问题"],
    advice: ["适当表达情感", "学会倾听他人", "保持自信的同时也要有同理心", "在领导中融入关怀"]
  },
  feminine: {
    name: "女性化",
    icon: "♀️",
    color: "#ec4899",
    description: "你的心理性别角色偏向女性化。你具有较强的同理心、温柔和关怀他人的能力，善于建立情感连接和维护人际关系。",
    traits: ["温柔体贴", "有同理心", "善于倾听", "有爱心", "善于维护关系"],
    strengths: ["人际关系好", "情感丰富", "善于沟通", "有耐心", "善于照顾他人"],
    advice: ["学会坚持自己的立场", "在关心他人的同时也要照顾自己", "培养独立决策能力", "不要过度牺牲自己"]
  },
  androgynous: {
    name: "双性化",
    icon: "⚧️",
    color: "#8b5cf6",
    description: "你的心理性别角色是双性化的，同时具有男性化和女性化的特质。这是最灵活的性别角色类型，你能够根据不同情境调整自己的行为方式。",
    traits: ["性格平衡", "适应力强", "既能独立又能合作", "既有理性又有感性", "灵活变通"],
    strengths: ["适应能力强", "人际交往能力强", "领导力与亲和力兼备", "情商高", "能够理解和包容不同观点"],
    advice: ["保持这种平衡", "继续发展多元能力", "成为他人的榜样", "珍惜这种灵活性"]
  },
  undifferentiated: {
    name: "未分化",
    icon: "⚪",
    color: "#6b7280",
    description: "你的心理性别角色尚未明确分化，男性化和女性化特质都不太明显。这可能意味着你还在探索自己的身份认同，或者你更倾向于中性化的表达方式。",
    traits: ["性格中性", "不太强调性别特质", "可能比较内敛", "可能还在探索自我"],
    strengths: ["不会被性别刻板印象束缚", "有自己的独特风格", "可能更客观中立"],
    advice: ["探索自己的特质和优势", "尝试发展更多元的能力", "不必刻意迎合性别期待", "找到适合自己的表达方式"]
  }
};